#Home Page Elements
login_button = "xpath=//a[contains(text(), 'Giriş Yap')]"
search_bar = "xpath=//input[@placeholder='Neyi ucuza almak istersin?']"
search_button = "xpath=//button[@title='Ara']"
user_icon = "xpath=//a[@id='H_a_v8']"
products_price_filter_text = "xpath=//b[contains(text(),'Fiyatı')]"
wishlist_button = "xpath=//span[normalize-space()='Takip Et']"
drop_wishlist_button = "xpath = //span[normalize-space()='Takibi Bırak']"
wishlist_navbar= "xpath//a[@id='H_f_v8']"
item_menu = "xpath=//i[@class='ItemMenu']"
delete_wish = "xpath=(//span[@class='hMenuItem deleteItem'][contains(text(),'Takibi Bırak')])[2]"
confirm_delete_wish = "xpath = (//b[contains(text(),'Takibi Bırak')])[1]"
book_name = "xpath = //h3[contains(text(),'Foucault Sarkacı - Umberto Eco')]"
first_product = "xpath=//b[contains(text(), 'Ürüne Git')]"
empty_wishlist = "xpath = //h2[contains(text(),'Takip listeniz şu anda boş!')]"
product_page= "xpath = //div[@id='pd_v8']"

